name: Scrape and Update Lunch

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: Run Scraper
        run: python3 scrapeYourPlate.py
      - name: Update Index
        run: python3 updateIndex.p
