name: Scrape 

on:
  schedule:
  - cron: "02 7 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Scrape menu information
        env:
          key: '${{ secrets.KEY }}'
        run: |
          python ./scripts/scrapeYourPlate.py
      - name: Upate index.html with lunch info
        env:
          key: '${{ secrets.KEY }}'
          workspace: ''
        run:
           python ./scripts/updateIndex.py

      - name: check for changes
        run: git status
      
      - name: stage changed files
        run: git add ./website/dist/index.html

      - name: commit changed files
        run: 
          git config --global user.name ${{ secrets.COMMIT_AUTHOR }}
          git config --global user.email ${{ secrets.COMMIT_AUTHOR_EMAIL }}
          git commit -m "Lunch update"
    
      - name: fetch from main
        run: git fetch origin main

      - name: push code to main
        run: git push origin HEAD:main
      