name: Scrape 

on:
  schedule:
  - cron: "02 7 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Scrape menu information
        env:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BETTERMENU_75F1F }}'
          client_id: '${{ secrets.CLIENT_ID }}'
          client_email: '${{ secrets.CLIENT_EMAIL }}'
          client_x509_cert_url: '${{ secrets.CLIENT_X509_CERT_URL }}' 
          project_id: '${{ secrets.PROJECT_ID }}'
          private_key_id: '${{ secrets.PRIVATE_KEY_ID}}'
        run: |
          python ./scripts/scrapeYourPlate.py